image:
  tag: v2.0-30-g0fdb905b35-dirty
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
  - host: cb.demo.acaisoft.io
    paths:
    - /
  tls:
  - secretName: cb-demo-acaisoft-io-tls
    hosts:
    - cb.demo.acaisoft.io